
services:
  mongodb:
    image: mongo:8.0.6
    ports:
      - "27017:27017"
    networks:
      - movies-network
    volumes:
      - db:/data/db
      - ./movies-backend-docker/mongo-seed:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456

  backend:
      image: cedric450/tp2-2292170-backend:${BACKEND_VERSION}
      build:
        context: ./movies-backend-docker
      ports:
        - "8787:8787"
      networks:
        - movies-network
      depends_on:
        - mongodb
      environment:
        - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_URL}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
        - SERVER_PORT=8787

  frontend:
      image: cedric450/tp2-2292170-frontend:${BACKEND_VERSION}
      build:
        context: ./movies-frontend-docker
      ports:
        - "80:80"
      depends_on:
        - backend
      networks:
        - movies-network

volumes:
  db:

networks:
  movies-network:
    driver: bridge